### ISSUE TITLE
[DSM] Sat Oct 07 2023

### ISSUE THREAD

**Issue by atls-github** [atls/dsm#1344]
## Шаблон
`#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии`
`#### Какие задачи будешь делать сегодня? Укажи #issues`
`#### Что тебя блокирует? (Этот пункт используется когда тебя что-то блокирует)`
`#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)`

**Comment by shifuwww** [comment]
**Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии**
 - https://github.com/house-of-hamsters/web/issues/15(Продумываю домен, с какими доменами будет взаимодействовать (Изучаю ддд))
 **Какие задачи будешь делать сегодня? Укажи #issues**
 - https://github.com/house-of-hamsters/web/issues/15(Продумываю домен, с какими доменами будет взаимодействовать

**Comment by RimidalU** [comment]
#### Какие задачи выполнял вчера? 
- https://github.com/house-of-hamsters/web/issues/20
> интеграционные тесты
#### Какие задачи будешь делать сегодня? 
- https://github.com/house-of-hamsters/web/issues/20
> добить интеграционные тесты 
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня?
с 16.00  мск

**Comment by akhioo** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
https://github.com/house-of-hamsters/web/issues/13 (Разбирал проблему инпута)
#### Какие задачи будешь делать сегодня? Укажи #issues
https://github.com/house-of-hamsters/web/issues/13 (Не разобрал проблему инпута, пишу тесты для application-module handlers)
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? 
15:00 - 17:00~18:00

**Comment by soldatviktimnosti** [comment]
Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии

https://github.com/delta-doc/infrastructure/issues/7 (уточнял задание)

Какие задачи будешь делать сегодня? Укажи #issues


https://github.com/delta-doc/infrastructure/issues/7 (подробно расписываю свой план действий в issues, разбираю для себя все пошагово и приступаю к работе)

Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня?

16:00 - 17:00. Но под вопросом, вероятно отменится. Все остальное время буду на работе.

**Comment by oksssvv** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/delta-doc/web/issues/110
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/delta-doc/web/issues/110

**Comment by aliceinapple** [comment]
#### Какие задачи выполнял вчера? 
+ https://github.com/delta-doc/web/issues/108
#### Какие задачи будешь делать сегодня?
+ https://github.com/delta-doc/web/issues/108
