### ISSUE TITLE
[DSM] Sat Nov 11 2023

### ISSUE THREAD

**Issue by atls-github** [atls/dsm#1370]
## Шаблон
`#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии`
`#### Какие задачи будешь делать сегодня? Укажи #issues`
`#### Что тебя блокирует? (Этот пункт используется когда тебя что-то блокирует)`
`#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)`

**Comment by eantdz** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
https://github.com/delta-doc/infrastructure/issues/22 - решено изменением версии чарта.
#### Какие задачи будешь делать сегодня? Укажи #issues
https://github.com/delta-doc/infrastructure/issues/27
