### ISSUE TITLE
[DSM] Fri Jan 26 2024

### ISSUE THREAD

**Issue by archeon-atls** [atls/dsm#1427]
## Шаблон
`#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии`
`#### Какие задачи будешь делать сегодня? Укажи #issues`
`#### Что тебя блокирует? (Этот пункт используется когда тебя что-то блокирует)`
`#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)`

**Comment by aliceinapple** [comment]
#### Какие задачи выполнял вчера?
+ https://github.com/atls/ecoscreen/issues/11
+ https://github.com/nuym-hr/web/issues/2
#### Какие задачи будешь делать сегодня? 
+ https://github.com/nuym-hr/web/issues/2
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня?
~ до 18.00 - 19.00 мск афк

**Comment by FrankJaskon** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии

- https://github.com/delta-doc/web/issues/360
- https://github.com/delta-doc/web/issues/357
- https://github.com/atls/reactjs/issues/139

#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/delta-doc/web/issues/355
- https://github.com/delta-doc/web/issues/359
- https://github.com/atls/reactjs/issues/139

**Comment by SlumberyDude** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/atls-arch/registry/issues/26
- https://github.com/atls/migration-bot/issues/76 начал разбираться с ботом
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/atls-arch/registry/issues/26
- https://github.com/atls/migration-bot/issues/76
- https://github.com/atls/migration-bot/issues/77

**Comment by AtamyratBabayev** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
* https://github.com/atls/keep-mindful/issues/12 - осталось добавить состояния для батареи
* https://github.com/atls/keep-mindful/issues/29
* https://github.com/atls/keep-mindful/issues/4 - на ревью
* https://github.com/atls/keep-mindful/issues/5 - на ревью
* https://github.com/atls/keep-mindful/issues/6 - на ревью
* https://github.com/atls/keep-mindful/issues/7 - на ревью
* https://github.com/atls/keep-mindful/issues/2 - на ревью

#### Какие задачи будешь делать сегодня? Укажи #issues
* https://github.com/atls/keep-mindful/issues/12 - осталось добавить состояния для батареи
* https://github.com/atls/keep-mindful/issues/29
* https://github.com/atls/keep-mindful/issues/30

**Comment by oksssvv** [comment]
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/nuym-hr/web/issues/1
- https://github.com/nuym-hr/web/issues/3
- https://github.com/delta-doc/web/issues/349
- https://github.com/delta-doc/web/issues/344

**Comment by RimidalU** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/atls-arch/registry/issues/26
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/atls-arch/registry/issues/26
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? 
13.00 ~ 15.00 мск

**Comment by Amiditin** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/delta-doc/web/issues/354
- https://github.com/delta-doc/web/issues/356
- https://github.com/delta-doc/web/issues/358
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/delta-doc/web/issues/354
- https://github.com/delta-doc/web/issues/325
