### ISSUE TITLE
[DSM] Mon Jan 29 2024

### ISSUE THREAD

**Issue by archeon-atls** [atls/dsm#1428]
## Шаблон
`#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии`
`#### Какие задачи будешь делать сегодня? Укажи #issues`
`#### Что тебя блокирует? (Этот пункт используется когда тебя что-то блокирует)`
`#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)`

**Comment by SlumberyDude** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/atls/migration-bot/issues/76 Пытался поправить баг минимальными изменениями, безуспешно. Похоже придется переписывать основную логику сессии и сервиса сессии на визард и сцену.
- https://github.com/atls-arch/registry/issues/27 ревью схемы
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/atls/migration-bot/issues/76
- https://github.com/atls-arch/registry/issues/27

**Comment by FrankJaskon** [comment]
#### Какие задачи будешь делать сегодня? Укажи #issues

- https://github.com/delta-doc/web/issues/353
- https://github.com/atls/reactjs/issues/139

**Comment by AtamyratBabayev** [comment]
#### Какие задачи будешь делать сегодня? Укажи #issues
* https://github.com/atls/keep-mindful/issues/29
* https://github.com/atls/keep-mindful/issues/30

**Comment by aliceinapple** [comment]
#### Какие задачи будешь делать сегодня? 
+ https://github.com/atls/ecoscreen/issues/11
+ https://github.com/nuym-hr/web/issues/2
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня?
16.30 - 18.30 мск

**Comment by oksssvv** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/nuym-hr/web/issues/3 
(add icons,button,input,switch,layout,utils,condition,text)
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/nuym-hr/web/issues/3
- https://github.com/nuym-hr/web/issues/1 (убрать ошибку тайпчека)
- https://github.com/delta-doc/web/issues/344
- https://github.com/delta-doc/web/issues/349
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? 
- 10:30 - 12:30 afk

**Comment by Nelfimov** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/atls/buildpacks/issues/13

#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/atls/buildpacks/issues/13
- https://github.com/atls/buildpacks/issues/12

**Comment by pfeilerer** [comment]
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/atls-design/planning/issues/264
- https://github.com/atls-design/planning/issues/254
- https://github.com/atls-design/planning/issues/252
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)
до 13:00

**Comment by RimidalU** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/atls-arch/registry/issues/26
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/atls-arch/registry/issues/26
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? 
13.00 ~ 15.00 мск

**Comment by Amiditin** [comment]
#### Какие задачи будешь делать сегодня? Укажи #issues 
- https://github.com/delta-doc/web/issues/354
- https://github.com/delta-doc/web/issues/325
- https://github.com/GoodGantt/web/issues/271
- https://github.com/GoodGantt/web/issues/272
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)
После 20:00 МСК
