### ISSUE TITLE
[DSM] Tue Jan 30 2024

### ISSUE THREAD

**Issue by archeon-atls** [atls/dsm#1429]
## Шаблон
`#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии`
`#### Какие задачи будешь делать сегодня? Укажи #issues`
`#### Что тебя блокирует? (Этот пункт используется когда тебя что-то блокирует)`
`#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)`

**Comment by FrankJaskon** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии

- https://github.com/delta-doc/web/issues/355

#### Какие задачи будешь делать сегодня? Укажи #issues

- https://github.com/delta-doc/web/issues/355
- https://github.com/atls/reactjs/issues/139

**Comment by AtamyratBabayev** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
* https://github.com/atls/keep-mindful/issues/29
* https://github.com/atls/keep-mindful/issues/30
#### Какие задачи будешь делать сегодня? Укажи #issues
* https://github.com/atls/keep-mindful/issues/4
* https://github.com/atls/keep-mindful/issues/30
* https://github.com/atls/keep-mindful/issues/6
* https://github.com/atls/keep-mindful/issues/8
* https://github.com/atls/keep-mindful/issues/11
* https://github.com/atls/keep-mindful/issues/5

**Comment by pfeilerer** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/atls-design/planning/issues/269
- https://github.com/atls-design/planning/issues/264
- https://github.com/atls-design/planning/issues/254
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/atls-design/planning/issues/269
- https://github.com/atls-design/planning/issues/252
- https://github.com/atls-design/planning/issues/256

**Comment by RimidalU** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/atls-arch/registry/issues/26
- https://github.com/atls-arch/registry/pull/29
- https://github.com/atls/ecoscreen/issues/13
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/atls-arch/registry/issues/26
- https://github.com/atls-arch/registry/pull/29
- https://github.com/atls/ecoscreen/issues/13
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? 
13.00 ~ 15.00 мск

**Comment by SlumberyDude** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/atls-arch/registry/issues/32 тезисно накида компонентов и технологий необходимых для реализации
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/atls/ecoscreen/issues/13
- https://github.com/atls-arch/registry/issues/32

**Comment by aliceinapple** [comment]
#### Какие задачи выполнял вчера?
+ https://github.com/atls/ecoscreen/issues/11
+ https://github.com/nuym-hr/web/issues/2
#### Какие задачи будешь делать сегодня? 
+ https://github.com/atls/ecoscreen/issues/11 - правки
+ https://github.com/nuym-hr/web/issues/2 - правки

**Comment by Nelfimov** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/atls/buildpacks/issues/13
- https://github.com/atls/buildpacks/issues/12

#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/atls/tools/issues/288

**Comment by Amiditin** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/delta-doc/web/issues/354
- https://github.com/GoodGantt/web/issues/271
- https://github.com/GoodGantt/web/issues/272
- https://github.com/GoodGantt/web/issues/235
#### Какие задачи будешь делать сегодня? Укажи #issues 
- https://github.com/GoodGantt/web/issues/271
- https://github.com/GoodGantt/web/issues/235
- https://github.com/torin-asakura/misik/issues/113

**Comment by oksssvv** [comment]
#### Какие задачи выполнял вчера? 
- https://github.com/nuym-hr/web/issues/1 (добавление шрифтов,доработка значений темы, обновление версий)
- https://github.com/nuym-hr/web/issues/3 (добавление и кастомизация select, divider, checkbox, энтрипоинт для тестирования ui компонентов)
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/nuym-hr/web/issues/1 (обновить версии)
- https://github.com/nuym-hr/web/issues/3 (добавить оставшиеся компоненты)
- https://github.com/delta-doc/web/issues/344 (исправить ошибку релиза)
- https://github.com/delta-doc/web/issues/349 (стиль кнопок сайдбара и проверка темы редактора документа)
