### ISSUE TITLE
[DSM] Wed Jan 31 2024

### ISSUE THREAD

**Issue by archeon-atls** [atls/dsm#1430]
## Шаблон
`#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии`
`#### Какие задачи будешь делать сегодня? Укажи #issues`
`#### Что тебя блокирует? (Этот пункт используется когда тебя что-то блокирует)`
`#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)`

**Comment by pfeilerer** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/atls-design/planning/issues/269
- https://github.com/atls-design/planning/issues/252
- https://github.com/atls-design/planning/issues/258
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/atls-design/planning/issues/269
- https://github.com/atls-design/planning/issues/252
- https://github.com/atls-design/planning/issues/264
- https://github.com/atls-design/planning/issues/254
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)
После 20:00

**Comment by RimidalU** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/atls-arch/registry/issues/26
- https://github.com/atls-arch/registry/pull/29
- https://github.com/atls/ecoscreen/issues/13
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/atls-arch/registry/issues/26
- https://github.com/atls-arch/registry/pull/29
- https://github.com/atls/ecoscreen/issues/13
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? 
13.00 ~ 15.00 мск

**Comment by SlumberyDude** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/atls-arch/registry/issues/32 Выделил домены, и ресурсы необходимые для разработки бекенда
- https://github.com/atls/ecoscreen/issues/13 Провел ревью доменного слоя
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/atls-arch/registry/issues/32
- https://github.com/atls/ecoscreen/issues/13
- https://github.com/atls/migration-bot/issues/76

**Comment by FrankJaskon** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии

- https://github.com/delta-doc/web/issues/355
- https://github.com/atls/reactjs/issues/139

#### Какие задачи будешь делать сегодня? Укажи #issues

- https://github.com/atls/reactjs/issues/139
- https://github.com/house-of-hamsters/web/issues/84

**Comment by oksssvv** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/nuym-hr/web/issues/1
- https://github.com/nuym-hr/web/issues/3 
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/nuym-hr/web/issues/3
- https://github.com/delta-doc/web/issues/344
- https://github.com/delta-doc/web/issues/349

**Comment by aliceinapple** [comment]
#### Какие задачи выполнял вчера?
+ https://github.com/atls/ecoscreen/issues/11
+ https://github.com/nuym-hr/web/issues/2
+ https://github.com/nuym-hr/web/issues/6
#### Какие задачи будешь делать сегодня? 
+ https://github.com/nuym-hr/web/issues/6

**Comment by AtamyratBabayev** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
* https://github.com/atls/keep-mindful/issues/35
#### Какие задачи будешь делать сегодня? Укажи #issues
* https://github.com/atls/keep-mindful/issues/35
* https://github.com/atls/keep-mindful/issues/5

**Comment by Amiditin** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/GoodGantt/web/issues/275
- https://github.com/GoodGantt/web/issues/271
- https://github.com/GoodGantt/web/issues/235
- https://github.com/torin-asakura/misik/issues/113
- https://github.com/torin-asakura/dream-team/issues/112
#### Какие задачи будешь делать сегодня? Укажи #issues 
- https://github.com/torin-asakura/misik/issues/113
- https://github.com/torin-asakura/dream-team/issues/112
- https://github.com/torin-asakura/dream-team/issues/113
