### ISSUE TITLE
[DSM] Tue Feb 06 2024

### ISSUE THREAD

**Issue by archeon-atls** [atls/dsm#1434]
## Шаблон
`#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии`
`#### Какие задачи будешь делать сегодня? Укажи #issues`
`#### Что тебя блокирует? (Этот пункт используется когда тебя что-то блокирует)`
`#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)`

**Comment by pfeilerer** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/delta-doc/web/issues/381
- https://github.com/delta-doc/web/issues/338
- https://github.com/atls-design/planning/issues/252
- https://github.com/atls-design/planning/issues/261
- https://velichar.atlassian.net/browse/RES-15
- https://velichar.atlassian.net/browse/RES-16
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/atls-design/planning/issues/252
- https://github.com/atls-design/planning/issues/261
- https://velichar.atlassian.net/browse/RES-4
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)
После 19:00 - переезд

**Comment by RimidalU** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/atls-arch/registry/issues/26
- https://github.com/atls-arch/registry/issues/31
- https://github.com/atls-arch/registry/issues/36
- https://github.com/atls/ecoscreen/issues/13
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/atls/ecoscreen/issues/13
- https://github.com/atls-arch/registry/issues/36
- https://github.com/atls-arch/registry/issues/38
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? 
13.00 ~ 15.00 мск

**Comment by aliceinapple** [comment]
#### Какие задачи выполнял вчера? 
+ https://github.com/nuym-hr/web/issues/6
#### Какие задачи будешь делать сегодня?
+ https://github.com/nuym-hr/web/issues/6
+ https://github.com/nuym-hr/web/issues/12

**Comment by SlumberyDude** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/atls-arch/registry/issues/36 Провел ревью схемы
- https://github.com/atls/migration-bot/issues/76 Начал рефактор. Новый объект сессии и переписал А0 на визард
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/atls-arch/registry/issues/36
- https://github.com/atls/migration-bot/issues/76
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)
Созвон только после 20:00 МСК

**Comment by Amiditin** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/torin-asakura/misik/issues/113
- https://github.com/GoodGantt/web/issues/208
- https://github.com/delta-doc/web/issues/380
- https://github.com/delta-doc/web/issues/375
- https://github.com/delta-doc/web/issues/376
- https://github.com/delta-doc/web/issues/379
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/delta-doc/web/issues/387

**Comment by AtamyratBabayev** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
 * https://github.com/atls/keep-mindful/issues/45
 * https://github.com/atls/keep-mindful/issues/43

#### Какие задачи будешь делать сегодня? Укажи #issues
 * https://github.com/atls/keep-mindful/issues/45
 * https://github.com/atls/keep-mindful/issues/47

**Comment by pussypistolss** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/torin-asakura/dream-team/issues/118
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/torin-asakura/dream-team/issues/118
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? 
17:00-19:00 поход к врачу
