### ISSUE TITLE
[DSM] Wed Feb 07 2024

### ISSUE THREAD

**Issue by archeon-atls** [atls/dsm#1435]
## Шаблон
`#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии`
`#### Какие задачи будешь делать сегодня? Укажи #issues`
`#### Что тебя блокирует? (Этот пункт используется когда тебя что-то блокирует)`
`#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)`

**Comment by SlumberyDude** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/atls-arch/registry/issues/31 ревью
- https://github.com/atls-arch/registry/issues/36 ревью
- https://github.com/atls-arch/registry/issues/38 ревью
- https://github.com/atls/migration-bot/issues/76 продолжил делать А1, реализовал возврат к началу на `/start` из визарда
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/atls/migration-bot/issues/76
- https://github.com/atls-arch/registry/issues/38
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)
- Созвоны только после 18 МСК

**Comment by FrankJaskon** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии

- https://github.com/delta-doc/web/issues/338

#### Какие задачи будешь делать сегодня? Укажи #issues

- https://github.com/delta-doc/web/issues/338

**Comment by aliceinapple** [comment]
#### Какие задачи выполнял вчера? 
+ https://github.com/nuym-hr/web/issues/6
+ https://github.com/nuym-hr/web/issues/12
#### Какие задачи будешь делать сегодня?
+ https://github.com/nuym-hr/web/issues/12
+ https://github.com/nuym-hr/web/issues/13

**Comment by AtamyratBabayev** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
 * https://github.com/atls/keep-mindful/issues/45 - добавить тесты
 * https://github.com/atls/keep-mindful/issues/47

#### Какие задачи будешь делать сегодня? Укажи #issues
 * https://github.com/atls/keep-mindful/issues/45
 * https://github.com/atls/keep-mindful/issues/47

**Comment by RimidalU** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/atls-arch/registry/issues/26
- https://github.com/atls-arch/registry/issues/31
> done
- https://github.com/atls-arch/registry/issues/36
> done
- https://github.com/atls/ecoscreen/issues/13
- https://github.com/atls-arch/registry/issues/38
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/atls/ecoscreen/issues/13
- https://github.com/atls-arch/registry/issues/40
- https://github.com/atls-arch/registry/issues/38
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? 
14.00 ~ 16.00 мск

**Comment by oksssvv** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/nuym-hr/web/issues/3
- https://github.com/nuym-hr/web/issues/9
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/nuym-hr/web/issues/11
- https://github.com/nuym-hr/web/issues/9

**Comment by pussypistolss** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/torin-asakura/dream-team/issues/118
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/torin-asakura/dream-team/issues/118

**Comment by Amiditin** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/delta-doc/web/issues/387
- https://github.com/delta-doc/web/issues/372
#### Какие задачи будешь делать сегодня? Укажи #issues
- Сравнение версий ганта, диагностика бага power-up 
  - https://t.me/c/1057842456/42128/57952 
  - https://github.com/GoodGantt/web/issues/294
  - https://github.com/GoodGantt/web/issues/293
