### ISSUE TITLE
[DSM] Sat Feb 10 2024

### ISSUE THREAD

**Issue by archeon-atls** [atls/dsm#1438]
## Шаблон
`#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии`
`#### Какие задачи будешь делать сегодня? Укажи #issues`
`#### Что тебя блокирует? (Этот пункт используется когда тебя что-то блокирует)`
`#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)`

**Comment by eantdz** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
https://github.com/GoodGantt/web/issues/297 - ПР и проверка traefik + mysql.
https://github.com/nuym-hr/bot/issues/4 - ПР и проверка CI, затем настройка CD. Инфра поднята.
#### Какие задачи будешь делать сегодня? Укажи #issues
https://github.com/GoodGantt/web/issues/297
https://github.com/nuym-hr/bot/issues/4 
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)
После 17:00 на 3-4ч. неактив.
