### ISSUE TITLE
[DSM] Tue Feb 27 2024

### ISSUE THREAD

**Issue by archeon-atls** [atls/dsm#1443]
## Шаблон
`#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии`
`#### Какие задачи будешь делать сегодня? Укажи #issues`
`#### Что тебя блокирует? (Этот пункт используется когда тебя что-то блокирует)`
`#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)`

**Comment by pfeilerer** [comment]
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://velichar.atlassian.net/browse/RES-9
- https://velichar.atlassian.net/browse/RES-10
- https://velichar.atlassian.net/browse/RES-8
- https://github.com/atls-design/planning/issues/272
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)
18:00 - 20:00 буду инет нормальный подключать

**Comment by RimidalU** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/nuym-hr/web/issues/21
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/nuym-hr/web/issues/21
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? 
13.00 ~ 15.00 мск

**Comment by FrankJaskon** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии

- https://github.com/delta-doc/web/issues/325

#### Какие задачи будешь делать сегодня? Укажи #issues

- https://github.com/delta-doc/web/issues/325

**Comment by aliceinapple** [comment]
#### Какие задачи выполнял вчера? 
+ https://github.com/candify-tech/web/issues/18
#### Какие задачи будешь делать сегодня? 
+ https://github.com/candify-tech/web/issues/18
+ https://github.com/candify-tech/web/issues/31

**Comment by Amiditin** [comment]
#### Какие задачи выполнял вчера? 
- https://github.com/GoodGantt/web/issues/340
- https://github.com/GoodGantt/web/issues/296
- https://github.com/candify-tech/web/issues/28
#### Какие задачи будешь делать сегодня?
- https://github.com/candify-tech/web/issues/28

**Comment by oksssvv** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/candify-tech/web/issues/26
- https://github.com/candify-tech/web/issues/27
- https://github.com/candify-tech/web/issues/9
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/candify-tech/web/issues/27
- https://github.com/candify-tech/web/issues/32
