### ISSUE TITLE
[DSM] Wed Feb 28 2024

### ISSUE THREAD

**Issue by archeon-atls** [atls/dsm#1444]
## Шаблон
`#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии`
`#### Какие задачи будешь делать сегодня? Укажи #issues`
`#### Что тебя блокирует? (Этот пункт используется когда тебя что-то блокирует)`
`#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)`

**Comment by RimidalU** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/nuym-hr/web/issues/21
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/nuym-hr/web/issues/21
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? 
13.00 ~ 15.00 мск

**Comment by eantdz** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
https://github.com/atls/infrastructure/issues/119 - в работе
#### Какие задачи будешь делать сегодня? Укажи #issues
https://github.com/candify-tech/infrastructure/issues/7
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)
09-18 - частично в работе
18-20 - АФК
20-23 - в работе

**Comment by badbaka** [comment]
Какие задачи выполнял вчера?
alt/infrastructure#119

Какие задачи будешь делать сегодня?
alt/infrastructure#119

Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня?
С 8 до 18,причина:дорабатываю последнюю неделю. Буду работать с 18 до 2-х.

**Comment by pussypistolss** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии

- https://github.com/torin-asakura/dream-team/pull/121

#### Какие задачи будешь делать сегодня? Укажи #issues

- https://github.com/torin-asakura/dream-team/pull/121

#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)

19:00 ~ 21:00 мск

**Comment by aliceinapple** [comment]
#### Какие задачи выполнял вчера? 
+ https://github.com/candify-tech/web/issues/18
+ https://github.com/candify-tech/web/issues/31
#### Какие задачи будешь делать сегодня? 
+ https://github.com/candify-tech/web/issues/31
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? 
17.00 - 20.00 мск

**Comment by pfeilerer** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://velichar.atlassian.net/browse/RES-9
- https://velichar.atlassian.net/browse/RES-10
- https://velichar.atlassian.net/browse/RES-8
- https://github.com/atls-design/planning/issues/272
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://velichar.atlassian.net/browse/RES-9
- https://velichar.atlassian.net/browse/RES-10
- https://velichar.atlassian.net/browse/RES-8
- https://github.com/atls-design/planning/issues/272
#### Есть ли личные дела из-за которых нужно отсутствовать на рабочем месте в течение рабочего дня? (Этот пункт используется когда дела есть)
16:00-18:00 буду в больнице

**Comment by Amiditin** [comment]
#### Какие задачи выполнял вчера? 
- https://github.com/candify-tech/web/issues/28
#### Какие задачи будешь делать сегодня?
- https://github.com/candify-tech/web/issues/28

**Comment by oksssvv** [comment]
#### Какие задачи выполнял вчера? Укажи #issues и сообщи в каком они состоянии
- https://github.com/candify-tech/web/issues/27
- https://github.com/candify-tech/web/issues/32
#### Какие задачи будешь делать сегодня? Укажи #issues
- https://github.com/candify-tech/web/issues/27
- https://github.com/candify-tech/web/issues/26
- https://github.com/candify-tech/web/issues/9
- https://github.com/candify-tech/web/issues/32
